### ISSUE TITLE
Currency conversion doesn't work

### ISSUE THREAD

**Issue by thebodzio** [awamper/google-calculator#6]
Recently I noticed that currency conversion started to fail completely with message:

`GoogleCalculator:convert(): Could not convert`

It happens regardless of the used query, e.g. `2$`, `3$$`, `1 USD to EUR` etc.

**Comment by awamper** [comment]
Yes, google broke it.

**Comment by thebodzio** [comment]
That was my guess, but I wanted to let you know nonetheless :}

I hope you'll find time to make the appropriate changes.

Thank you for your effort and truly nice and useful extension!

**Comment by thebodzio** [comment]
Thank you! 👍
